package com.ctrip.zeus.dao.mapper;

import com.ctrip.zeus.dao.entity.StatusCheckCountSlb;
import com.ctrip.zeus.dao.entity.StatusCheckCountSlbExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StatusCheckCountSlbMapper {
    long countByExample(StatusCheckCountSlbExample example);

    int deleteByExample(StatusCheckCountSlbExample example);

    int deleteByPrimaryKey(Long id);

    int insert(StatusCheckCountSlb record);

    int insertSelective(StatusCheckCountSlb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_check_count_slb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    StatusCheckCountSlb selectOneByExample(StatusCheckCountSlbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_check_count_slb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    StatusCheckCountSlb selectOneByExampleSelective(@Param("example") StatusCheckCountSlbExample example, @Param("selective") StatusCheckCountSlb.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_check_count_slb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<StatusCheckCountSlb> selectByExampleSelective(@Param("example") StatusCheckCountSlbExample example, @Param("selective") StatusCheckCountSlb.Column... selective);

    List<StatusCheckCountSlb> selectByExample(StatusCheckCountSlbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_check_count_slb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    StatusCheckCountSlb selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") StatusCheckCountSlb.Column... selective);

    StatusCheckCountSlb selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") StatusCheckCountSlb record, @Param("example") StatusCheckCountSlbExample example);

    int updateByExample(@Param("record") StatusCheckCountSlb record, @Param("example") StatusCheckCountSlbExample example);

    int updateByPrimaryKeySelective(StatusCheckCountSlb record);

    int updateByPrimaryKey(StatusCheckCountSlb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_check_count_slb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(StatusCheckCountSlb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_check_count_slb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(StatusCheckCountSlb record);

    /*Self Defined*/
    int updateDataSetById(List<StatusCheckCountSlb> records);

    int updateCountBySlb(StatusCheckCountSlb record);

    int batchInsert(List<StatusCheckCountSlb> records);
}