package com.ctrip.zeus.dao.mapper;

import com.ctrip.zeus.dao.entity.WafInstallFile;
import com.ctrip.zeus.dao.entity.WafInstallFileExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WafInstallFileMapper {
    long countByExample(WafInstallFileExample example);

    int deleteByExample(WafInstallFileExample example);

    int deleteByPrimaryKey(Long id);

    int insert(WafInstallFile record);

    int insertSelective(WafInstallFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waf_install_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WafInstallFile selectOneByExample(WafInstallFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waf_install_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WafInstallFile selectOneByExampleSelective(@Param("example") WafInstallFileExample example, @Param("selective") WafInstallFile.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waf_install_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WafInstallFile selectOneByExampleWithBLOBs(WafInstallFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waf_install_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<WafInstallFile> selectByExampleSelective(@Param("example") WafInstallFileExample example, @Param("selective") WafInstallFile.Column ... selective);

    List<WafInstallFile> selectByExampleWithBLOBs(WafInstallFileExample example);

    List<WafInstallFile> selectByExample(WafInstallFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waf_install_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WafInstallFile selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") WafInstallFile.Column ... selective);

    WafInstallFile selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") WafInstallFile record, @Param("example") WafInstallFileExample example);

    int updateByExampleWithBLOBs(@Param("record") WafInstallFile record, @Param("example") WafInstallFileExample example);

    int updateByExample(@Param("record") WafInstallFile record, @Param("example") WafInstallFileExample example);

    int updateByPrimaryKeySelective(WafInstallFile record);

    int updateByPrimaryKeyWithBLOBs(WafInstallFile record);

    int updateByPrimaryKey(WafInstallFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waf_install_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(WafInstallFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waf_install_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(WafInstallFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waf_install_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertWithBLOBs(WafInstallFile record);
}